version: '3.8'
services:
  php:
    image: test-php
    container_name: php-uat-test
    build:
        context: php
        dockerfile: Dockerfile
    volumes:
         - ./:/var/www/html/
         - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
         - my-session:/var/www/html/sessions
    environment:
         - PHP_FPM_ENABLE=1
         - PHP_FPM_SERVER_ADDR=php
         - PHP_FPM_SERVER_PORT=9000
         - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
         - DB_HOST=${HOST_LOCAL}
         - DB_NAME=${DB_NAME}
         - DB_USER=${DB_USER}
         - DB_PASS=${PASSWORD_LOCAL}
         - DB_PORT=3306
    ports:
            - 8000:80 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: ${HOST_LOCAL}
    ports:
      - "8080:80"
volumes:
  my-data: 
  my-session:
   